var MENU = {
  burgers: [
    {
      id: "the-gramercy-tavern-burger-4-pack",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
      name: "DOM SALADA",
      dsc: "The Gramercy Tavern Burger - 4 Pack",
      price: 17,
    },
    {
      id: "shake-shack-shackburger-8-pack",
      img: "./img/cardapio/burguers/shake-shack-shackburger-8-pack.973a5e26836ea86d7e86a327becea2b0.jpg",
      name: "DOM SALADA ESPECIAL",
      dsc: "Shake Shack ShackBurger® - 8 Pack",
      price: 20,
    },
    {
      id: "gotts-cheeseburger-kit-for-4",
      img: "./img/cardapio/burguers/gotts-complete-cheeseburger-kit-for-4.7bdc74104b193427b3fe6eae39e05b5e.jpg",
      name: "DOM SALADA DUPLO",
      dsc: "Gott's Complete Cheeseburger Kit for 4",
      price: 23,
    },
    {
      id: "le-big-matt-kit-for-6",
      img: "./img/cardapio/burguers/le-big-matt-kit-for-6.1ddae6e382bb3218eeb0fd5247de115a.jpg",
      name: "DOM BACON",
      dsc: "Le Big Matt Burger Kit for 6",
      price: 22,
    },
    {
      id: "shake-shack-shackburger-16-pack",
      img: "./img/cardapio/burguers/shake-shack-shackburger-16-pack.316f8b09144db65931ea29e34869287a.jpg",
      name: "DOM BACON ESPECIAL",
      dsc: "Shake Shack Shackburger® - 16 Pack",
      price: 22,
    },
    {
      id: "21-usda-prime-burgers-pack-of-18-8oz-each",
      img: "./img/cardapio/burguers/usda-prime-burgers-pack-of-18-8oz-each.274c67f15aa1c0b210dbf51801706670.jpg",
      name: "DOM EGG BACON",
      dsc: "USDA Prime Burgers - Pack of 18 (8oz each)",
      price: 24,
    },
    {
      id: "double-stack-burger-kit-for-4",
      img: "./img/cardapio/burguers/handf-double-stack-burger-kit-for-4.4ee9f54b1d6087e9996335f07c13e5cd.jpg",
      name: "DOM CAMPO GRANDE",
      dsc: "Double Stack Burger Kit for 4",
      price: 20,
    },
    {
      id: "goldbelly-burger-bash-pack",
      img: "./img/cardapio/burguers/the-burger-bash-package.bd9d12d031865940bbe5faf15f1a62f8.jpg",
      name: "DOM BURGUER",
      dsc: 'Goldbelly "Burger Bash" Pack',
      price: 15,
    },
    {
      id: "burger-au-poivre-kit-4-pack",
      img: "./img/cardapio/burguers/burger-au-poivre-kit-4-pack.3ca0e39b02db753304cd185638dad518.jpg",
      name: "DOM MISTO QUENTE",
      dsc: "Burger Au Poivre Kit - 4 Pack",
      price: 15,
    },
    {
      id: "goldbelly-burger-blend-4-lbs",
      img: "./img/cardapio/burguers/goldbelly-burger-blend-1-lb.13a21b66edf7173a59c75c3a6d2f981b.jpg",
      name: "DOM BAGUNÇA",
      dsc: "Goldbelly Burger Blend - 4 lbs.",
      price: 25,
    },
    {
      id: "gotts-complete-cheeseburger-kit-for-8",
      img: "./img/cardapio/burguers/gotts-complete-cheeseburger-kit-for-8.092aa049d00286fa1733d720decc782e.jpg",
      name: "DOM CALABRESA",
      dsc: "Gott's Complete Cheeseburger Kit for 8",
      price: 20,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM CALABRESA TURBO",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 24,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM X-TUDO",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 32,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM GARCIA",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 24,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM PAULISTA",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 26,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM FRANGO BAGUNÇA",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 25,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM FRANGO",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 17,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM FRANGO ESPECIAL",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 20,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM FRANGO SUPER",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 25,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM OLAVO",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 25,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "DOM PONTA DE PEITO",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 31,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "HOT DOG SIMPLES PRENSADO",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 12,
    },
    {
      id: "gramercy-tavern-burger-kielbasa-combo",
      img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-47.jpg",
      name: "HOT DOG DUPLO PRENSADO",
      dsc: "Gramercy Tavern Burger + Kielbasa Combo",
      price: 15,
    },
  ],
  bebidas: [
    {
      id: "hong-kong-boba-tea-kit-for-6",
      img: "./img/cardapio/bebidas/hong-kong-boba-tea-kit-for-6.63841de36d8e5edfafa13023fc303285.jpg",
      name: "Coca Cola Lata 350ml",
      dsc: "Hong Kong Boba Tea Kit for 6",
      price: 5.0,
    },
    {
      id: "guys-caliente-margaritas-for-12",
      img: "./img/cardapio/bebidas/guys-caliente-margaritas-for-12.ca8c6bc06b8f1039549385ffcebc749d.jpg",
      name: "Fanta Lata 350ml",
      dsc: "Guy's Caliente Margaritas for 12",
      price: 5,
    },
    {
      id: "woodford-reserve-mint-julep-syrup",
      img: "./img/cardapio/bebidas/woodford-reserve-mint-julep-syrup.ef523ac7cbae5f4aba6b058207f490d2.jpg",
      name: "Guarána Antartica 350ml",
      dsc: "Woodford Reserve Mint Julep Syrup",
      price: 5,
    },
    {
      id: "new-orleans-hurricane-mix",
      img: "./img/cardapio/bebidas/new-orleans-hurricane-mix.4613584fc65cb0787024dd24d2a8f4b3.jpg",
      name: "Coca Cola 2l",
      dsc: "New Orleans Hurricane Mix",
      price: 15,
    },
    {
      id: "margarita-mix",
      img: "./img/cardapio/bebidas/margarita-mix.bd48a000d589d3147b14790af3c33fcd.jpg",
      name: "Fanta Laranja 2l",
      dsc: "Margarita Mix",
      price: 13,
    },
    {
      id: "woodford-reserve-mint-julep-syrup-2-pack",
      img: "./img/cardapio/bebidas/woodford-reserve-mint-julep-syrup-2-pack.0ac76063f151988113cbaabd0eaa829f.jpg",
      name: "Woodford Reserve",
      dsc: "Fanta Uva 2l",
      price: 13,
    },
    {
      id: "unicorn-parade-milkshake-kit-for-8",
      img: "./img/cardapio/bebidas/unicorn-parade-milkshake-kit-for-2.9052d04c1cf25b29442048bd3e535f21.jpg",
      name: "Sprit 2l",
      dsc: "Unicorn Parade Milkshake Kit for 8",
      price: 13,
    },
    {
      id: "chickpea-chiller-kit-for-6",
      img: "./img/cardapio/bebidas/chickpea-chiller-kit-for-6.4310765c71ba524b5462ea9330d32446.jpg",
      name: "Guaraná Antarctica 2l",
      dsc: "Chickpea Chiller Kit for 6",
      price: 15,
    },
    {
      id: "15194-old-honey-barn-mint-julep-mixer-200ml",
      img: "./img/cardapio/bebidas/old-honey-barn-mint-julep-mixer-200ml.e0b131d6d9b69963706b43fd4334ab74.jpg",
      name: "Água sem Gás 310ml",
      dsc: "Old Honey Barn Mint Julep Mixer - 200ml Flask",
      price: 4,
    },
    {
      id: "kentucky-derby-mint-julep-gift-set",
      img: "./img/cardapio/bebidas/kentucky-derby-mint-julep-gift-set.79720eda4e9c8e3fcf9ecb5c79827f2c.jpg",
      name: "Água com Gás 310ml",
      dsc: "Kentucky Derby Mint Julep Gift Set",
      price: 4,
    },
    {
      id: "002-charleston-bloody-mary-mix-weekender-bold-and-spicy",
      img: "./img/cardapio/bebidas/weekender-charleston-bloody-mary-mix-bold-and-spicy.c372868c9937e407a299a22001e210e2.jpg",
      name: "Suco Lata",
      dsc: "Weekender | Charleston Bloody Mary Mix Bold & Spicy",
      price: 7,
    },
    {
      id: "nola-cold-brew-concentrate-bag-in-box",
      img: "./img/cardapio/bebidas/nola-cold-brew-concentrate-bag-in-box.3df6fde8bd83f29235565984ae8ed22b.jpg",
      name: "Coca Cola Litro 1l",
      dsc: "NOLA Cold Brew Concentrate Bag-in-Box",
      price: 8,
    },
    {
      id: "nola-cold-brew-concentrate-bag-in-box",
      img: "./img/cardapio/bebidas/nola-cold-brew-concentrate-bag-in-box.3df6fde8bd83f29235565984ae8ed22b.jpg",
      name: "Funada",
      dsc: "NOLA Cold Brew Concentrate Bag-in-Box",
      price: 8,
    },
  ],
};
